### ISSUE TITLE
Groups: Add leader checkbox to member list

### ISSUE THREAD

**Issue by ChrisChasm** [ChasmSolutions/disciple-tools#102]
This way we can indicate which people are leaders of the group.

**Comment by ChrisChasm** [comment]
- Member (default)
- Leader

**Comment by ChrisChasm** [comment]
- [ ]  Remove P2P meta 'unbelieving, etc'
- [ ]  Add leadership indicator to p2p
- [ ]  Change meta box 4 fields to read from contact not from p2p info.

**Comment by ChrisChasm** [comment]
All has been updated. [Commit](https://github.com/ChasmSolutions/disciple-tools/pull/115)
