### ISSUE TITLE
Location Upgrade Path

### ISSUE THREAD

**Issue by ChrisChasm** [ChasmSolutions/disciple-tools#110]
We need to create a progress strategy for a project to have a large area set of locations (i.e. state level) and then later in the project be able to subdivide and work at lower administrative district level (i.e. county or tract level).

So we need to build the ability for upgrades.

**Comment by ChrisChasm** [comment]
We might consider installing all locations in a progression, so that even if you want to go straight to the county level, you have to go through the state level installation.

**Comment by ChrisChasm** [comment]
- [ ] Create Admin 1 and Admin 2 levels for USA, Morocco, Tunisia
  - [ ] Admin 1 USA
  - [ ] Admin 2 USA
  - [ ] Admin 1 Tunisia
  - [ ] Admin 2 Tunisia
  - [ ] Admin 1 Morocco
  - [ ] Admin 2 Morocco
- [ ] Host them on S3
- [ ] Build install wizard that starts with highest admin area and works down to lowest.

**Comment by ChrisChasm** [comment]
[Consolidated the locations functions](https://github.com/ChasmSolutions/disciple-tools/commit/b91863ee923bb9036e9bfa8effe67546d79a9b6e)

**Comment by ChrisChasm** [comment]
There is a lot of work going on right now with normalizing area definitions. We can build a model on what is planned,but will have to update the records once they finish their work. @JustinLong

**Comment by ChrisChasm** [comment]
Install script built. Now creating insert scripts.

**Comment by ChrisChasm** [comment]
This movement mapping project is the outcome of this effort. It will provide a stable api and buffer for the mapping sources. 
https://github.com/ChasmSolutions/movement-mapping

**Comment by ChrisChasm** [comment]
After a very long effort. We are pausing further dev into coordinating the locations and mapping. So much of the organization and resources needed to tie into the mapping is not available. There is so much work left to do with the mapping on the ground, that we have just done a version for the US and for T. So this will have to be closed and reopened later when we can push it further down the track.
